### ISSUE TITLE
sea temperature anomaly not displayed

### ISSUE THREAD

**Issue by cgharo** [ICATMAR/HFRadar#55]
advance interface, when I select the temperature anomaly is not shown

**Comment by gerardllorach** [comment]
Current day is not offered by the product sometimes --> Show this information to the user.
Fixed timeScaleCorrection for SST anomaly as it was not needed in the first place (forecast and historic WMS links are the same) d6f6305a717bd351efd57af63207aa2cb23df313

**Comment by gerardllorach** [comment]
#100 shows that the layer is not available
